### ISSUE TITLE
db.remove does not work in dballe 7.35-1 and 7.36-1

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/dballe#152] opened 2019-01-23 15:16 UTC
db.remove has stopped working, and does nothing. It works in version 7.33-2 only if within the db.query_data loop (see comment in attached code here). In version 7.35-1 (and 7.36-1) it raises a "transaction in transaction error".

         da_cancellare = list()
         for row in db.query_data(dballe.Record(**options)):
             if row[options['var']] > threshold:
                 del row['ana_id']
                 del row['context_id']
                 da_cancellare.append(row)
                 # db.remove(row) raise a "transaction in transaction error"
         for row in da_cancellare:
             db.remove(row)
         db.vacuum()

file:///autofs/nethomes/lbressan/Programmi/POST_PROCESSING/db_test.dapulire.sqlite3

**Comment by edigiacomo** [comment] 2019-01-23 17:28
Duplicate of #145

**Closed by edigiacomo** 2019-01-23 17:28 UTC
